// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migration4removeemailfromcustomerandemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration4removeemailfromcustomerandemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201909051415210_migration4removeemailfromcustomerandemployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
