// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migrationupdateonemployeetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationupdateonemployeetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201909061407555_migration update on employee table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
